# Utiliser l'image officielle PHP 8.2 FPM comme image de base
FROM php:8.2-fpm

# Définir le répertoire de travail à /app/backend
WORKDIR /app/backend

# Installer les dépendances nécessaires
RUN apt-get update && \
    apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libpq-dev \
    libonig-dev \
    libicu-dev && \
    docker-php-ext-install pdo_mysql intl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN echo "extension=intl.so" >> /usr/local/etc/php/conf.d/docker-php-ext-intl.ini

# Installer Composer globalement
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copier les fichiers de l'application
COPY ./backend ./

# Installer les dépendances PHP en mode production
RUN composer install --no-dev --optimize-autoloader

# Exposer le port 9000 pour PHP-FPM
EXPOSE 9000

# Démarrer PHP-FPM
CMD ["php-fpm"]