# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN npm install --omit=dev

# Copy application source
COPY frontend/ ./

# Build the application
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Set the entrypoint
CMD ["npm", "start"]