# api/config/packages/security.yaml
security:
  # https://symfony.com/doc/current/security.html#c-hashing-passwords
  password_hashers:
    App\Entity\User: 'auto'

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    users:
      entity:
        class: App\Entity\User
        property: email
      # mongodb:
      #    class: App\Document\User
      #    property: email

  firewalls:
    dev:
      pattern: ^/_(profiler|wdt)
      security: false
    main:
      pattern: ^/api # Exclure les requêtes vers /admin
      stateless: true
      provider: users
      entry_point: jwt
      json_login:
        check_path: auth # The name in routes.yaml is enough for mapping
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt: ~
      refresh_jwt: 
        check_path: gesdinet_jwt_refresh_token
        provider: users

    admin:
      pattern: ^/admin
      provider: users
      stateless: false
      form_login:
        login_path: /admin/login
        check_path: /admin/login
        default_target_path: /admin
        enable_csrf: true
        csrf_token_id: authenticate
      logout:
        path: /admin/logout
        target: /admin/login
      # Désactivez stateless pour permettre l'utilisation de sessions

  access_control:
    - { path: ^/api/events/public, roles: PUBLIC_ACCESS }
    - { path: ^/api/user/email, roles: PUBLIC_ACCESS }
    - { path: ^/$, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI
    - { path: ^/api/users, roles: PUBLIC_ACCESS, methods: [POST] } # Allows accessing the Swagger UI docs
    - { path: ^/api/docs, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI docs
    - { path: ^/api/auth, roles: PUBLIC_ACCESS }
    - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
    - { path: ^/admin/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
