import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navigation/navbar";
import { EventProvider } from "@/components/EventContext";
import Footer from "@/components/layout/footer";

import { inter } from '@/app/fonts/fonts';
import { k2d } from '@/app/fonts/fonts';

export const metadata: Metadata = {
  title: "Eventify",
  description: "Generated by create next app",
  // favicon
  icons: {
    icon: "/images/logo_eventify.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased min-h-screen`}
      >
        <Navbar />
        <EventProvider>
          <main className="flex-grow">{children}</main>
        </EventProvider>
        <Footer />
      </body>
    </html>
  );
}
